# Site settings
title:          London Data Science Co-op
description:    "Comunity of Data Scientists, Software and Machine Learning Engineers"

# Author
author:
  name:         LDS Co-op
  url:          https://ldscoop.github.io
  email:        london.data.science.co.op@gmail.com

# Build settings
markdown:       kramdown
remote_theme:   chesterhow/tale

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
